name: 'Birthday Bot Helper'
description: 'Action to extract dates from a json file and if it matches with current date, create output for a slack message.'
inputs:
  sheet-data:
    description: 'Data from google-sheets'
    required: true
  purpose:
    description: 'Whether the helper is being used for the reminder or for the birthday wish. Can be one of reminder or wish'
    required: false
    default: wish
outputs:
  messageList: # id of output
    description: 'List of messages to be posted to the slack channel.'
runs:
  using: 'node16'
  main: 'index.js'